### ISSUE TITLE
license

### ISSUE THREAD

**Issue by dgreisen** [isandunk/Onyx-Graphical-Assets#1]
Hi,

Thanks for creating this, it is very helpful. Could you add a license document, so we know the licensing terms? 

Thank you,

David Greisen

**Comment by isandunk** [comment]
Thanks David glad I could be of help!

I've added this license to the repo: http://creativecommons.org/licenses/by-sa/3.0/deed.en_GB.

Closing the issue. Cheers.

**Comment by dgreisen** [comment]
Thanks for the quick response. Would you be willing to consider dual licensing under the same license as enyo (http://www.apache.org/licenses/LICENSE-2.0.html)? that would greatly simplify license compliance when using your icons.

**Comment by dgreisen** [comment]
Just wanted to follow up. We are unable to ascertain how the cc license interacts with the apache license, and therefore cannot use your icons in our project under the current license. We would be happy to contribute some icons (such as user, tag, save and delete) if you are willing to dual license under the apache license. 

Thank you for your consideration.

**Comment by isandunk** [comment]
Thanks for your patience David. I've updated the readme to indicate the update to the licence, so now they should be compatible, and I will add the actual txt licence a bit later on.

Looking forward to your additions!

Cheers.
