### ISSUE TITLE
Request: Volume, Mute, and Play button

### ISSUE THREAD

**Issue by JayCanuck** [isandunk/Onyx-Graphical-Assets#3]
I'd love to see a Volume, Mute, and Play icons added to the repo. Would be really handy :)

**Comment by isandunk** [comment]
Thanks for the suggestion Jason, I'll get those worked up and into the repo soon(ish!).

**Comment by isandunk** [comment]
Hi Jason, I've just finished working up those three items (see b84ea5a81dba7e2196e6feb988c9d0c8867701c8) - they are now available in the examples PSD and folder as 72dpi PNGs. 

Closing now.

Cheers!
