### ISSUE TITLE
I would request a "Refresh" icon. Thanks.

### ISSUE THREAD

**Issue by rexzh** [isandunk/Onyx-Graphical-Assets#4]

**Comment by isandunk** [comment]
I'll see what I can do!

Cheers.

**Comment by isandunk** [comment]
Hi @rexzh, just added a couple of variants of the refresh icon with ca72cf0acf2f9c19bd2a53a4645ac1d9e37a5203

Closing the issue now - cheers!

**Comment by rexzh** [comment]
great, thanks a lot.

-----Original Message-----
